### ISSUE TITLE
Support for Invoice and Payment Process

### ISSUE THREAD

**Issue by toddapetersen** [gocloud1001/netsuite-authorize.net-connect#1]
The current code base only supports authorizing CCD's for Cash Sales.  It would be nice if it also supported Invoice and Payment transactions for those of us who issue payment terms and also accept credit cards as a form of payment.

**Comment by gocloud1001** [comment]
Current version does support Payment transaction against an Invoice using Authorize.net.  It also supports Deposits on Sales Orders that can be applied later to Invoices.

Releasing very shortly is 3.1.beta - which also supports eCheck (ACH) via Authorize.net as well as a default payment method to aid in the management of customers with multiple payment methods.
